spring:
  datasource:
    # 数据库访问配置，使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/localhostdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  thymeleaf:
    #开启模板缓存（默认值：true）
    cache: false
    #Check that the template exists before rendering it.
    check-template: true
    #检查模板位置是否正确（默认值:true）
    check-template-location: true
    #Content-Type的值（默认值：text/html）
    #content-type: text/html
    #开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
    #模板编码
    encoding: UTF-8
    #要被排除在解析之外的视图名称列表，用逗号分隔
    excluded-view-names:
    #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: HTML
    #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: classpath:/templates/
    #在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
    #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
    template-resolver-order:
    #可解析的视图名称列表，用逗号分隔
    #view-names: